# Generated by Django 5.0.6 on 2024-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iharoonapp", "0002_chapter_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="quiz",
            field=models.IntegerField(null=True),
        ),
    ]
