# Generated by Django 5.0.6 on 2024-06-22 04:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iharoonapp", "0003_alter_chapter_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="img",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="quiz",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
