# Generated by Django 5.0.6 on 2024-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iharoonapp", "0005_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
