# Generated by Django 5.0.6 on 2024-06-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iharoonapp", "0008_quiz_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="iharoonapp.chapter",
            ),
            preserve_default=False,
        ),
    ]
